# https://github.com/Un1Gfn/downloadsplit/blob/master/.circleci/config.yml
# https://github.com/Un1Gfn/walleyeboot/blob/master/.circleci/config.yml
# https://github.com/Un1Gfn/SSD-ci/blob/master/.circleci/config.yml

# https://circleci.com/gh/Un1Gfn/avx
# while true; do sleep 7; echo $RANDOM; done


# https://circleci.com/server/changelog/
version: 3
# version: 2
# version: 2.19.00

jobs:
  build:
    working_directory: ~/$CIRCLE_PROJECT_REPONAME
    docker:
      - image: ubuntu:eoan # 19.10 Eoan Ermine
    resource_class: small
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            apt update
            apt upgrade -y
            apt install -y wget gcc tree valgrind gdb vim
      # - run:
      #     name: Stop for SSH
      #     command: |
      #       false
      - run:
          name: Build and run
          command: |
            cd $WD
            ./clean.sh || true
            rm -fv result* || true
            ./make.sh && env AVX=1 ./a.out run 0 1000 10
            # ./make.sh && env AVX=1 ./a.out run 0 2000 20
      - store_artifacts:
          # https://circleci.com/docs/2.0/artifacts/#artifacts-overview
          path: $WD/result*
          destination: result