# https://github.com/Un1Gfn/downloadsplit/blob/master/.circleci/config.yml

# https://circleci.com/gh/Un1Gfn/avx
# while true; do sleep 7; echo $RANDOM; done

version: 2
jobs:
  build:
    environment:
    working_directory: ~/code
    docker:
      - image: ubuntu:eoan # 19.10 Eoan Ermine
      # - image: ubuntu:disco # 19.04 Disco Dingo
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            apt update
            apt upgrade -y
            apt install -y wget gcc tree valgrind gdb vim
      - run:
          name: Stop for SSH
          command: |
            false
          # no_output_timeout: 30m
          # no_output_timeout: 1.5h
      # - store_artifacts:
      #     # https://circleci.com/docs/2.0/artifacts/#artifacts-overview
      #     path: ~/split/
      #     destination: split